version: '3.2'

services:

#================================================================================================
# CORE-CONSUL
#================================================================================================
  consul:
    image: dockerframework/core-consul
    ports:
      - "8500:8500"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - CONSUL_OPTIONS=-server -bootstrap-expect 1 -client 0.0.0.0 -ui    # minimal server options

#================================================================================================
# SPARK
#================================================================================================
  spark-master:
    restart: always
    build:
      context: .
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - "4040:4040"
      - "6066:6066"
      - "7077:7077"
      - "${SPARK_CONSUL_SERVICEPORT_MASTER}:8080"
    depends_on:
      - consul
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - SPARK_HOME=${DATA_SPARK_MASTER}
      - SPARK_VERSION=${SPARK_VERSION}
      - HADOOP_VERSION=${HADOOP_VERSION}
      - CONSUL_AGENT=consul
      - CONSUL_SERVICENAME=${SPARK_CONSUL_SERVICENAME_MASTER}
      - CONSUL_SERVICETAGS=${SPARK_CONSUL_SERVICETAGS_MASTER}
      - CONSUL_SERVICEPORT=${SPARK_CONSUL_SERVICEPORT_MASTER}
      - CONSUL_CHECKTYPE=${SPARK_CONSUL_CHECKTYPE_MASTER}

  spark-worker:
    restart: always
    build:
      context: ./docker/spark/${SPARK_VERSION}
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - "${SPARK_CONSUL_SERVICEPORT_WORKER}:8081"
    depends_on:
      - consul
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - SPARK_HOME=${DATA_SPARK_WORKER}
      - SPARK_VERSION=${SPARK_VERSION}
      - HADOOP_VERSION=${HADOOP_VERSION}
      - CONSUL_AGENT=consul
      - CONSUL_SERVICENAME=${SPARK_CONSUL_SERVICENAME_WORKER}
      - CONSUL_SERVICETAGS=${SPARK_CONSUL_SERVICETAGS_WORKER}
      - CONSUL_SERVICEPORT=${SPARK_CONSUL_SERVICEPORT_WORKER}
      - CONSUL_CHECKTYPE=${SPARK_CONSUL_CHECKTYPE_WORKER}
      - SPARK_MASTERURL=${SPARK_MASTERURL}
